/* Copyright (c) 2011-2011 Sven van der Meer (sven@vandermeer.de)
 * All rights reserved.
 *
 * Redistribution  and  use  in  source  and  binary  forms,  with  or  without
 * modification, are permitted provided that the following conditions are met:
 * 
 *     + Redistributions of source code must retain the above copyright notice,
 *       this list of conditions and the following disclaimer.
 *     + Redistributions  in binary  form must  reproduce the  above copyright
 *       notice, this list  of conditions and  the following disclaimer  in the
 *       documentation and/or other materials provided with the distribution.
 *     + Neither  the  name  of  the  <ORGANIZATION>  nor  the  names  of   its
 *       contributors may be used to  endorse or promote products derived  from
 *       this software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS  IS"
 * AND ANY EXPRESS  OR IMPLIED WARRANTIES,  INCLUDING, BUT NOT  LIMITED TO, THE
 * IMPLIED WARRANTIES OF MERCHANTABILITY  AND FITNESS FOR A  PARTICULAR PURPOSE
 * ARE DISCLAIMED. IN  NO EVENT SHALL  THE COPYRIGHT HOLDER  OR CONTRIBUTORS BE
 * LIABLE  FOR  ANY  DIRECT,  INDIRECT,  INCIDENTAL,  SPECIAL,  EXEMPLARY,   OR
 * CONSEQUENTIAL  DAMAGES  (INCLUDING,  BUT  NOT  LIMITED  TO,  PROCUREMENT  OF
 * SUBSTITUTE GOODS  OR SERVICES;  LOSS OF  USE, DATA,  OR PROFITS; OR BUSINESS
 * INTERRUPTION) HOWEVER  CAUSED AND  ON ANY  THEORY OF  LIABILITY, WHETHER  IN
 * CONTRACT,  STRICT LIABILITY,  OR TORT  (INCLUDING NEGLIGENCE  OR OTHERWISE)
 * ARISING IN ANY WAY OUT OF THE  USE OF THIS SOFTWARE, EVEN IF ADVISED  OF THE
 * POSSIBILITY OF SUCH DAMAGE.
 * 
 * [The BSD License, http://www.opensource.org/licenses/bsd-license.php]
 */

 /*
  * This file is auto generated by org.skb.tribe.tools.GenerateLangTokens based on
  * the JSON input file defining the constants in:
  * V:\dev\skb\projects\lang\cola\proto/src/main/resources/org/skb/lang/cola/proto/proto.json
  *
  * Please do not change anything here, since the content of this file will be
  * replaced if the JSON base is changing and the file is re-generated.
  */
package org.skb.lang.cola.proto;

public final class ColaTokensConstants {
    public ColaTokensConstants(){}

    public final static String parserARRAY = "array";
    public final static String parserMEMBER = "member";
    public final static String parserIDENTIFIER = "identifier";
    public final static String parserScopedName = "scoped_name";
    public final static String parserBaseType  = "base_type";
    public final static String parserItemProp = "item-property";
    public final static String parserScopeSep = "::";
    public final static String gcMiscParrentID = "parrentId";
    public final static String gcMiscParrentCat = "parrentCategory";
    public final static String gcMiscCurrentCat = "currentCategory";
    public final static String gcMiscInDefinition = "inDefinition";
    public final static String gcMiscInItem = "inItem";
    public final static String gcMiscInContract = "inContract";
    public final static String gcMiscInPackage = "inPackage";
    public final static String gcMiscInElement = "inElement";
    public final static String gcMiscInFacility = "inFacility";
    public final static String gcMiscInAction = "inAction";
    public final static String gcMiscInStruct = "inStruct";
    public final static String gcMiscSpecName = "specificationName";
    public final static String gcMiscCurrentScope = "currentScope";
    public final static String colaACTION = "action";
    public final static String colaATTRIBUTE = "attribute";
    public final static String colaCONTRACT = "contract";
    public final static String colaDEFINITION = "definition";
    public final static String colaELEMENT = "element";
    public final static String colaFACILITY = "facility";
    public final static String colaFUNCTION = "function";
    public final static String colaINV = "inv";
    public final static String colaITEM = "item";
    public final static String colaMANDATORY = "mandatory";
    public final static String colaNOT_DEF = "not_def";
    public final static String colaOPTIONAL = "optional";
    public final static String colaPACKAGE = "package";
    public final static String colaPARAMETER = "parameter";
    public final static String colaPOST = "post";
    public final static String colaPRE = "pre";
    public final static String colaPROPERTY = "property";
    public final static String colaREQUIRED = "required";
    public final static String colaSPECIFICATION = "cola-specification";
    public final static String colaSTRUCT = "struct";
    public final static String colaTYPEDEF = "typedef";
    public final static String colaBINARY = "binary";
    public final static String colaBOOLEAN = "boolean";
    public final static String colaCHAR = "char";
    public final static String colaDOUBLE = "double";
    public final static String colaFLOAT = "float";
    public final static String colaHEX = "hex";
    public final static String colaINTEGER = "integer";
    public final static String colaLONG = "long";
    public final static String colaOCTET = "octet";
    public final static String colaSHORT = "short";
    public final static String colaSTRING = "string";
    public final static String colaVOID = "void";
    public final static String colaFALSE = "FALSE";
    public final static String colaNULL = "NULL";
    public final static String colaTRUE = "TRUE";
    public final static String colaAT_ALTERABLE = "@alterable";
    public final static String colaAT_APPLY = "@apply";
    public final static String colaAT_CLEVEL = "@clevel";
    public final static String colaAT_CONTAINS = "@contains";
    public final static String colaAT_DESCRIPTION = "@description";
    public final static String colaAT_EXTENDS = "@extends";
    public final static String colaAT_ENVIRONMENT = "@environment";
    public final static String colaAT_LANGUAGE = "@language";
    public final static String colaAT_NEGOTIABLE = "@negotiable";
    public final static String colaAT_PRIORITY = "@priority";
    public final static String colaAT_PROVIDES = "@provides";
    public final static String colaAT_RANK = "@rank";
    public final static String colaAT_REQUIRES = "@requires";
    public final static String colaAT_RETURN = "@return";
    public final static String colaAT_RUNTIME = "@runtime";
    public final static String colaAT_SCOPE = "@scope";
    public final static String colaAT_SPEC = "@scpec";
    public final static String colaAT_STAGE = "@stage";
    public final static String colaAT_TYPE = "@type";
    public final static String colaAT_VISIBILITY = "@visibility";
    public final static String colaCPP_DIRECTIVE = "preprocessor directive";
    public final static String colaESC = "escape sequence";
    public final static String colaFloatSuffix = "floating point suffix";
    public final static String colaHexDigit = "hexadecimal digit";
    public final static String colaIDENT = "identifier";
    public final static String colaINLINE_CODE = "inline code";
    public final static String colaML_COMMENT = "multiple line comment";
    public final static String colaOctDigit = "otcal digit";
    public final static String colaOctalEscape = "octal escape sequence";
    public final static String colaSL_COMMENT = "single line comment";
    public final static String colaUnicodeEscape = "unicode escape sequence";
    public final static String colaVAL_BINARY = "binary value";
    public final static String colaVAL_CHAR = "character value";
    public final static String colaVAL_FLOAT = "floating point value";
    public final static String colaVAL_HEX = "hexadecimal value";
    public final static String colaVAL_INTEGER = "integer value";
    public final static String colaVAL_OCT = "octal value";
    public final static String colaVAL_STRING = "string value";
    public final static String colaWS = "whitespace";
}
