/* Copyright (c) 2011-2011 Sven van der Meer (sven@vandermeer.de)
 * All rights reserved.
 *
 * Redistribution  and  use  in  source  and  binary  forms,  with  or  without
 * modification, are permitted provided that the following conditions are met:
 * 
 *     + Redistributions of source code must retain the above copyright notice,
 *       this list of conditions and the following disclaimer.
 *     + Redistributions  in binary  form must  reproduce the  above copyright
 *       notice, this list  of conditions and  the following disclaimer  in the
 *       documentation and/or other materials provided with the distribution.
 *     + Neither  the  name  of  the  <ORGANIZATION>  nor  the  names  of   its
 *       contributors may be used to  endorse or promote products derived  from
 *       this software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS  IS"
 * AND ANY EXPRESS  OR IMPLIED WARRANTIES,  INCLUDING, BUT NOT  LIMITED TO, THE
 * IMPLIED WARRANTIES OF MERCHANTABILITY  AND FITNESS FOR A  PARTICULAR PURPOSE
 * ARE DISCLAIMED. IN  NO EVENT SHALL  THE COPYRIGHT HOLDER  OR CONTRIBUTORS BE
 * LIABLE  FOR  ANY  DIRECT,  INDIRECT,  INCIDENTAL,  SPECIAL,  EXEMPLARY,   OR
 * CONSEQUENTIAL  DAMAGES  (INCLUDING,  BUT  NOT  LIMITED  TO,  PROCUREMENT  OF
 * SUBSTITUTE GOODS  OR SERVICES;  LOSS OF  USE, DATA,  OR PROFITS; OR BUSINESS
 * INTERRUPTION) HOWEVER  CAUSED AND  ON ANY  THEORY OF  LIABILITY, WHETHER  IN
 * CONTRACT,  STRICT LIABILITY,  OR TORT  (INCLUDING NEGLIGENCE  OR OTHERWISE)
 * ARISING IN ANY WAY OUT OF THE  USE OF THIS SOFTWARE, EVEN IF ADVISED  OF THE
 * POSSIBILITY OF SUCH DAMAGE.
 * 
 * [The BSD License, http://www.opensource.org/licenses/bsd-license.php]
 */

 /*
  * This file is auto generated by org.skb.tribe.tools.GenerateLangTokens based on
  * the JSON input file defining the constants in:
  * V:\dev\skb\projects\lang\cola\proto/src/main/resources/org/skb/lang/cola/proto/proto.json
  *
  * Please do not change anything here, since the content of this file will be
  * replaced if the JSON base is changing and the file is re-generated.
  */
package org.skb.lang.cola.proto;

public final class ColaRuleConstants {
    public ColaRuleConstants(){}

    public final static String ruleProperty01 = "property:01";
    public final static String ruleProperty02 = "property:02";
    public final static String ruleProperty03 = "property:03";
    public final static String ruleProperty04 = "property:04";
    public final static String ruleProperty05 = "property:05";
    public final static String ruleProperty06 = "property:06";
    public final static String ruleProperty07 = "property:07";
    public final static String ruleProperty08 = "property:08";
    public final static String ruleProperty09 = "property:09";
    public final static String ruleProperty10 = "property:10";
    public final static String ruleProperty11 = "property:11";
    public final static String ruleProperty12 = "property:12";
    public final static String ruleProperty13 = "property:13";
    public final static String ruleProperty14 = "property:14";
    public final static String ruleContract01 = "contract:01";
    public final static String ruleContract02 = "contract:02";
    public final static String ruleContract03 = "contract:03";
    public final static String ruleContract04 = "contract:04";
    public final static String ruleContract05 = "contract:05";
    public final static String ruleItem01 = "item:01";
    public final static String ruleItem02 = "item:02";
    public final static String ruleItem03 = "item:03";
    public final static String ruleItem04 = "item:04";
    public final static String ruleItem05 = "item:05";
    public final static String ruleItem06 = "item:06";
    public final static String ruleItem07 = "item:07";
    public final static String ruleItem08 = "item:08";
    public final static String ruleItem09 = "item:09";
    public final static String ruleItem10 = "item:10";
    public final static String ruleIdentifier01 = "identifier:01";
    public final static String ruleIdentifier02 = "identifier:02";
    public final static String ruleIdentifier03 = "identifier:03";
    public final static String ruleIdentifier04 = "identifier:04";
    public final static String ruleIdentifier05 = "identifier:05";
    public final static String ruleIdentifier06 = "identifier:06";
    public final static String ruleScopedName01 = "scoped-name:01";
    public final static String ruleScopedName02 = "scoped-name:02";
    public final static String ruleScopedName03 = "scoped-name:03";
    public final static String ruleScopedName04 = "scoped-name:04";
    public final static String ruleScopedName05 = "scoped-name:05";
    public final static String ruleScopedName06 = "scoped-name:06";
}
