/* Copyright (c) 2011-2011 Sven van der Meer (sven@vandermeer.de)
 * All rights reserved.
 *
 * Redistribution  and  use  in  source  and  binary  forms,  with  or  without
 * modification, are permitted provided that the following conditions are met:
 * 
 *     + Redistributions of source code must retain the above copyright notice,
 *       this list of conditions and the following disclaimer.
 *     + Redistributions  in binary  form must  reproduce the  above copyright
 *       notice, this list  of conditions and  the following disclaimer  in the
 *       documentation and/or other materials provided with the distribution.
 *     + Neither  the  name  of  the  <ORGANIZATION>  nor  the  names  of   its
 *       contributors may be used to  endorse or promote products derived  from
 *       this software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS  IS"
 * AND ANY EXPRESS  OR IMPLIED WARRANTIES,  INCLUDING, BUT NOT  LIMITED TO, THE
 * IMPLIED WARRANTIES OF MERCHANTABILITY  AND FITNESS FOR A  PARTICULAR PURPOSE
 * ARE DISCLAIMED. IN  NO EVENT SHALL  THE COPYRIGHT HOLDER  OR CONTRIBUTORS BE
 * LIABLE  FOR  ANY  DIRECT,  INDIRECT,  INCIDENTAL,  SPECIAL,  EXEMPLARY,   OR
 * CONSEQUENTIAL  DAMAGES  (INCLUDING,  BUT  NOT  LIMITED  TO,  PROCUREMENT  OF
 * SUBSTITUTE GOODS  OR SERVICES;  LOSS OF  USE, DATA,  OR PROFITS; OR BUSINESS
 * INTERRUPTION) HOWEVER  CAUSED AND  ON ANY  THEORY OF  LIABILITY, WHETHER  IN
 * CONTRACT,  STRICT LIABILITY,  OR TORT  (INCLUDING NEGLIGENCE  OR OTHERWISE)
 * ARISING IN ANY WAY OUT OF THE  USE OF THIS SOFTWARE, EVEN IF ADVISED  OF THE
 * POSSIBILITY OF SUCH DAMAGE.
 * 
 * [The BSD License, http://www.opensource.org/licenses/bsd-license.php]
 */

 /*
  * This file is auto generated by org.skb.tribe.tools.GenerateLangTokens based on
  * the JSON input file defining the constants in:
  * V:\dev\skb\projects\lang\pola\proto/src/main/resources/org/skb/lang/pola/proto/proto.json
  *
  * Please do not change anything here, since the content of this file will be
  * replaced if the JSON base is changing and the file is re-generated.
  */
package org.skb.lang.pola.proto;

public final class PolaTokensConstants {
    public PolaTokensConstants(){}

    public final static String parserARRAY = "array";
    public final static String parserMEMBER = "__member";
    public final static String parserIDENTIFIER = "identifier";
    public final static String parserScopedName = "scoped_name";
    public final static String parserBaseType  = "base_type";
    public final static String parserItemProp = "item-property";
    public final static String parserScopeSep = "::";
    public final static String gcMiscParrentID = "parrentId";
    public final static String gcMiscParrentCat = "parrentCategory";
    public final static String gcMiscCurrentCat = "currentCategory";
    public final static String gcMiscInDefinition = "inDefinition";
    public final static String gcMiscInItem = "inItem";
    public final static String gcMiscInContract = "inContract";
    public final static String gcMiscInPackage = "inPackage";
    public final static String gcMiscInElement = "inElement";
    public final static String gcMiscInFacility = "inFacility";
    public final static String gcMiscInAction = "inAction";
    public final static String gcMiscInStruct = "inStruct";
    public final static String gcMiscSpecName = "specificationName";
    public final static String gcMiscCurrentScope = "currentScope";
    public final static String polaACTION = "action";
    public final static String polaATTRIBUTE = "attribute";
    public final static String polaCONTRACT = "contract";
    public final static String polaELEMENT = "element";
    public final static String polaFACILITY = "facility";
    public final static String polaFUNCTION = "function";
    public final static String polaITEM = "item";
    public final static String polaMANDATORY = "mandatory";
    public final static String polaNOT_DEF = "not_def";
    public final static String polaOPTIONAL = "optional";
    public final static String polaPACKAGE = "package";
    public final static String polaPARAMETER = "parameter";
    public final static String polaPROPERTY = "property";
    public final static String polaREQUIRED = "required";
    public final static String polaSPECIFICATION = "pola-specification";
    public final static String polaSTRUCT = "struct";
    public final static String polaTYPEDEF = "typedef";
    public final static String polaBINARY = "binary";
    public final static String polaBOOLEAN = "boolean";
    public final static String polaCHAR = "char";
    public final static String polaDOUBLE = "double";
    public final static String polaFLOAT = "float";
    public final static String polaHEX = "hex";
    public final static String polaINTEGER = "integer";
    public final static String polaLONG = "long";
    public final static String polaOCTET = "octet";
    public final static String polaSHORT = "short";
    public final static String polaSTRING = "string";
    public final static String polaVOID = "void";
    public final static String polaFALSE = "FALSE";
    public final static String polaNULL = "NULL";
    public final static String polaTRUE = "TRUE";
    public final static String polaAT_ALTERABLE = "@alterable";
    public final static String polaAT_APPLY = "@apply";
    public final static String polaAT_CLEVEL = "@clevel";
    public final static String polaAT_CONTAINS = "@contains";
    public final static String polaAT_DESCRIPTION = "@description";
    public final static String polaAT_EXTENDS = "@extends";
    public final static String polaAT_ENVIRONMENT = "@environment";
    public final static String polaAT_LANGUAGE = "@language";
    public final static String polaAT_NEGOTIABLE = "@negotiable";
    public final static String polaAT_PRIORITY = "@priority";
    public final static String polaAT_PROVIDES = "@provides";
    public final static String polaAT_RANK = "@rank";
    public final static String polaAT_REQUIRES = "@requires";
    public final static String polaAT_RETURN = "@return";
    public final static String polaAT_RUNTIME = "@runtime";
    public final static String polaAT_SCOPE = "@scope";
    public final static String polaAT_SPEC = "@scpec";
    public final static String polaAT_STAGE = "@stage";
    public final static String polaAT_TYPE = "@type";
    public final static String polaAT_VISIBILITY = "@visibility";
    public final static String polaCPP_DIRECTIVE = "preprocessor directive";
    public final static String polaESC = "escape sequence";
    public final static String polaFloatSuffix = "floating point suffix";
    public final static String polaHexDigit = "hexadecimal digit";
    public final static String polaIDENT = "identifier";
    public final static String polaINLINE_CODE = "inline code";
    public final static String polaML_COMMENT = "multiple line comment";
    public final static String polaOctDigit = "otcal digit";
    public final static String polaOctalEscape = "octal escape sequence";
    public final static String polaSL_COMMENT = "single line comment";
    public final static String polaUnicodeEscape = "unicode escape sequence";
    public final static String polaVAL_BINARY = "binary value";
    public final static String polaVAL_CHAR = "character value";
    public final static String polaVAL_FLOAT = "floating point value";
    public final static String polaVAL_HEX = "hexadecimal value";
    public final static String polaVAL_INTEGER = "integer value";
    public final static String polaVAL_OCT = "octal value";
    public final static String polaVAL_STRING = "string value";
    public final static String polaWS = "whitespace";
}
