/* Copyright (c) 2011-2011 Sven van der Meer (sven@vandermeer.de)
 * All rights reserved.
 *
 * Redistribution  and  use  in  source  and  binary  forms,  with  or  without
 * modification, are permitted provided that the following conditions are met:
 * 
 *     + Redistributions of source code must retain the above copyright notice,
 *       this list of conditions and the following disclaimer.
 *     + Redistributions  in binary  form must  reproduce the  above copyright
 *       notice, this list  of conditions and  the following disclaimer  in the
 *       documentation and/or other materials provided with the distribution.
 *     + Neither  the  name  of  the  <ORGANIZATION>  nor  the  names  of   its
 *       contributors may be used to  endorse or promote products derived  from
 *       this software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS  IS"
 * AND ANY EXPRESS  OR IMPLIED WARRANTIES,  INCLUDING, BUT NOT  LIMITED TO, THE
 * IMPLIED WARRANTIES OF MERCHANTABILITY  AND FITNESS FOR A  PARTICULAR PURPOSE
 * ARE DISCLAIMED. IN  NO EVENT SHALL  THE COPYRIGHT HOLDER  OR CONTRIBUTORS BE
 * LIABLE  FOR  ANY  DIRECT,  INDIRECT,  INCIDENTAL,  SPECIAL,  EXEMPLARY,   OR
 * CONSEQUENTIAL  DAMAGES  (INCLUDING,  BUT  NOT  LIMITED  TO,  PROCUREMENT  OF
 * SUBSTITUTE GOODS  OR SERVICES;  LOSS OF  USE, DATA,  OR PROFITS; OR BUSINESS
 * INTERRUPTION) HOWEVER  CAUSED AND  ON ANY  THEORY OF  LIABILITY, WHETHER  IN
 * CONTRACT,  STRICT LIABILITY,  OR TORT  (INCLUDING NEGLIGENCE  OR OTHERWISE)
 * ARISING IN ANY WAY OUT OF THE  USE OF THIS SOFTWARE, EVEN IF ADVISED  OF THE
 * POSSIBILITY OF SUCH DAMAGE.
 * 
 * [The BSD License, http://www.opensource.org/licenses/bsd-license.php]
 */

 /*
  * This file is auto generated by org.skb.tribe.tools.GenerateLangTokens based on
  * the JSON input file defining the constants in:
  * V:\dev\skb\projects\lang\glue\proto/src/main/resources/org/skb/lang/glue/proto/proto.json
  *
  * Please do not change anything here, since the content of this file will be
  * replaced if the JSON base is changing and the file is re-generated.
  */
package org.skb.lang.glue.proto;

public final class GlueTokensConstants {
    public GlueTokensConstants(){}

    public final static String parserARRAY = "array";
    public final static String parserIDENTIFIER = "identifier";
    public final static String parserScopedName = "scoped_name";
    public final static String parserScopeSep = "::";
    public final static String gcMiscParrentID = "parrentId";
    public final static String gcMiscParrentCat = "parrentCategory";
    public final static String gcMiscCurrentCat = "currentCategory";
    public final static String gcMiscInDefinition = "inDefinition";
    public final static String gcMiscInItem = "inItem";
    public final static String gcMiscInContract = "inContract";
    public final static String gcMiscInPackage = "inPackage";
    public final static String gcMiscInElement = "inElement";
    public final static String gcMiscInFacility = "inFacility";
    public final static String gcMiscInAction = "inAction";
    public final static String gcMiscInStruct = "inStruct";
    public final static String gcMiscSpecName = "specificationName";
    public final static String gcMiscCurrentScope = "currentScope";
    public final static String glueTopology = "topology";
    public final static String glueNode = "node";
    public final static String glueConnection = "connection";
    public final static String glueInterface = "interface";
    public final static String glueComponent = "component";
    public final static String glueDirected = "directed";
    public final static String glueSource = "source";
    public final static String glueTarget = "target";
    public final static String gluePort = "port";
    public final static String glueSourcePort = "sourceport";
    public final static String glueTargetPort = "targetport";
    public final static String glueDomain = "domain";
    public final static String glueContracts = "contracts";
    public final static String gluePolicies = "policies";
    public final static String glueBINARY = "binary";
    public final static String glueBOOLEAN = "boolean";
    public final static String glueCHAR = "char";
    public final static String glueDOUBLE = "double";
    public final static String glueFLOAT = "float";
    public final static String glueHEX = "hex";
    public final static String glueINTEGER = "integer";
    public final static String glueLONG = "long";
    public final static String glueOCTET = "octet";
    public final static String glueSHORT = "short";
    public final static String glueSTRING = "string";
    public final static String glueVOID = "void";
    public final static String glueFALSE = "FALSE";
    public final static String glueNULL = "NULL";
    public final static String glueTRUE = "TRUE";
    public final static String glueCPP_DIRECTIVE = "preprocessor directive";
    public final static String glueESC = "escape sequence";
    public final static String glueFloatSuffix = "floating point suffix";
    public final static String glueHexDigit = "hexadecimal digit";
    public final static String glueIDENT = "identifier";
    public final static String glueINLINE_CODE = "inline code";
    public final static String glueML_COMMENT = "multiple line comment";
    public final static String glueOctDigit = "otcal digit";
    public final static String glueOctalEscape = "octal escape sequence";
    public final static String glueSL_COMMENT = "single line comment";
    public final static String glueUnicodeEscape = "unicode escape sequence";
    public final static String glueVAL_BINARY = "binary value";
    public final static String glueVAL_CHAR = "character value";
    public final static String glueVAL_FLOAT = "floating point value";
    public final static String glueVAL_HEX = "hexadecimal value";
    public final static String glueVAL_INTEGER = "integer value";
    public final static String glueVAL_OCT = "octal value";
    public final static String glueVAL_STRING = "string value";
    public final static String glueWS = "whitespace";
}
